export const language = {
	en: {
		add: `Add`,
		allocateYield: `Allocate Your Yield`,
		allocation: `Allocation`,
		allocationSummaryDescription: `Below represents how you are currently allocating your AO Yield.`,
		aoAudit: `AO Specific Audits`,
		aoClaim: `AO Claim`,
		arweaveAddress: `Arweave Address`,
		backToMint: `Back to Mint`,
		balancesHeader: `Balances`,
		baseContractAudits: `Base Contract Audits`,
		build: `Build`,
		circulatingSupply: `Circulating AO Supply`,
		close: `Close`,
		connectWallet: `Connect Wallet`,
		credBalance: `Wallet CRED Balance`,
		currentBalance: `Current balance`,
		deposit: `Deposit`,
		depositedSteth: `Deposited StETH`,
		deposits: `Deposits`,
		dismiss: `Dismiss`,
		disconnect: `Disconnect`,
		edit: `Edit`,
		executing: `Executing`,
		fairLaunch: `100% Fair Launch`,
		fairLaunchDeposits: `100% Fair Launch`,
		fetching: `Fetching`,
		fetchingAoSupply: `Fetching AO Supply`,
		fetchingRewards: `Fetching reward amounts`,
		fetchingTotalSteth: `Fetching Total Steth`,
		gigaArmstrongInfo: `AO tokens are ultra scarce. At launch, there are only 1.03m of them. For comparison, there are 120 million Ether, 461 million Solana, and 55 billion Ripple tokens. You may prefer to refer to AO quantities in giga-Armstrongs -- 1,000,000,000 of its smallest units. Armstrongs are similar to Satoshis in Bitcoin.`,
		landingHeader1: `Hyper.`,
		landingHeader2: `Parallel.`,
		landingHeader3: `Computer.`,
		landingSubheader: `A decentralized super computer inspired by the actor-oriented paradigm, integrated with Arweave's data storage capabilities.`,
		loading: `Loading`,
		max: `Max`,
		messages: `Messages`,
		mint: `Mint`,
		network: `Network`,
		noWalletsConnected: `No wallets connected`,
		nodes: `Nodes`,
		pageNotFound: `Page not found`,
		pasteFromClipboard: `Paste from clipboard`,
		phase: `Phase`,
		processes: `Processes`,
		read: `Read`,
		recipient: `Recipient`,
		remove: `Remove`,
		status: `Status`,
		steth: `stETH`,
		stethConversion: `Buy stETH`,
		stethMinting: `Mint stETH`,
		summary: `Summary`,
		walletBalance: `Wallet balance`,
		walletsConnected: `Wallets connected`,
		withdraw: `Withdraw`,
		yield: `Yield`,
	},
};
