export const language = {
	en: {
		aoAudit: `AO Specific Audits`,
		aoClaim: `AO Claim`,
		arweaveAddress: `Arweave address`,
		calculator: `Calculator`,
		circulatingSupply: `Circulating AO Supply`,
		close: `Close`,
		connectWallet: `Connect Wallet`,
		credBalance: `Wallet CRED Balance`,
		currentBalance: `Current balance`,
		deposit: `Deposit`,
		depositedSteth: `Deposited StETH`,
		dismiss: `Dismiss`,
		disconnect: `Disconnect`,
		executing: `Executing`,
		fetching: `Fetching`,
		fetchingAoSupply: `Fetching AO Supply`,
		fetchingRewards: `Fetching reward amounts`,
		fetchingTotalSteth: `Fetching Total Steth`,
		gigaArmstrongInfo: `AO tokens are ultra scarce. At launch, there are only 1.03m of them. For comparison, there are 120 million Ether, 461 million Solana, and 55 billion Ripple tokens. You may prefer to refer to AO quantities in giga-Armstrongs -- 1,000,000,000 of its smallest units. Armstrongs are similar to Satoshis in Bitcoin.`,
		loading: `Loading`,
		max: `Max`,
		baseContractAudits: `Base Contract Audits`,
		pageNotFound: `Page not found`,
		pasteFromClipboard: `Paste from clipboard`,
		recipient: `Recipient`,
		withdraw: `Withdraw`,
		walletBalance: `Wallet balance`,
		walletsConnected: `Wallets connected`,
		noWalletsConnected: `No wallets connected`,
		steth: `stETH`,
		stethConversion: `Buy stETH`,
		stethMinting: `Mint stETH`,
	},
};
