export const language = {
	en: {
		aoAudit: `AO Specific Audits`,
		aoClaim: `AO Claim`,
		arweaveAddress: `Arweave address`,
		calculator: `Calculator`,
		circulatingSupply: `Circulating AO Supply`,
		close: `Close`,
		connectWallet: `Connect Wallet`,
		credBalance: `Wallet CRED Balance`,
		currentBalance: `Current balance`,
		deposit: `Deposit`,
		depositedSteth: `Deposited StETH`,
		dismiss: `Dismiss`,
		disconnect: `Disconnect`,
		executing: `Executing`,
		fetching: `Fetching`,
		fetchingRewards: `Fetching reward amounts`,
		gigaArmstrongInfo: `One giga-armstrong represents 1,000,000,000 armstrongs. Armstrong is the smallest denomination of AO - similar to satoshi for Bitcoin or wei for Ethereum.`,
		loading: `Loading`,
		max: `Max`,
		baseContractAudits: `Base Contract Audits`,
		pageNotFound: `Page not found`,
		pasteFromClipboard: `Paste from clipboard`,
		recipient: `Recipient`,
		submit: `Submit`,
		walletBalance: `Wallet balance`,
		walletNotConnected: `Wallet not connected`,
		steth: `stETH`,
		stethConversion: `Convert ETH to stETH here`,
	},
};
