import { DefaultTheme } from 'styled-components';

export const lightTheme = {
	scheme: 'light',
	positive1: '#279200',
	positive2: '#217A00',
	caution1: '#EEB700',
	negative1: '#D0234F',
	negative2: '#BD1A43',
	neutral1: '#FFFFFF',
	neutral2: '#F7F7F8',
	neutral3: '#F0F1F1',
	neutral4: '#E6E6E6',
	neutral5: '#D6D6D6',
	neutral6: '#CCCCCC',
	neutral7: '#808080',
	neutral8: '#6E6E6E',
	neutral9: '#616161',
	neutralA1: '#000000',
	neutralA2: '#333333',
	neutralA3: '#3D3D3D',
	neutralA4: '#474747',
	neutralA5: '#525252',
	neutralA6: '#666666',
	neutralA7: '#707070',
	overlay1: 'rgb(0, 0, 0, .45)',
	overlay2: 'rgb(0, 0, 0, .5)',
	shadow1: 'rgb(150, 150, 150, .5)',
	shadow2: 'rgb(75, 75, 75, .5)',
	primary1: '#105A00',
	primary2: '#217A00',
	accent1: '#279200',
	accent2: '#217A00',
	light1: '#FFFFFF',
	light2: '#DADADA',
	light3: '#B3B3B3',
	dark1: '#151515',
	dark2: '#333333',
	link1: '#3344FF',
	link2: '#091DFF',
	chart1: '#C78135',
	chart2: '#FBF5EE',
	stats: {
		primary: '#5bd1f4',
		alt1: '#289cd3',
		alt2: '#197ab8',
		alt3: '#0e5b90',
		alt4: '#053951',
		alt5: '#072714',
		alt6: '#d9c128',
		alt7: '#cadd33',
		alt8: '#b6ea44',
		alt9: '#94e54c',
		alt10: '#63cf5e',
		alt11: '#36ad7b',
		alt12: '#5bd1f4',
		alt13: '#289cd3',
		alt14: '#197ab8',
		alt15: '#0e5b90',
		alt16: '#053951',
		alt17: '#072714',
	},
};

export const theme = (currentTheme: any): DefaultTheme => ({
	scheme: currentTheme.scheme,
	colors: {
		accordion: {
			background: currentTheme.neutral1,
			hover: currentTheme.neutral2,
			color: currentTheme.neutralA1,
		},
		border: {
			primary: currentTheme.neutral4,
			alt1: currentTheme.neutral5,
			alt2: currentTheme.neutral6,
			alt3: currentTheme.neutral7,
			alt4: currentTheme.neutral8,
			alt5: currentTheme.accent1,
			alt6: currentTheme.accent2,
		},
		button: {
			primary: {
				background: currentTheme.neutral1,
				border: currentTheme.neutral4,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutral2,
					border: currentTheme.neutral5,
					color: currentTheme.neutralA1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral5,
					color: currentTheme.neutral7,
				},
			},
			alt1: {
				background: currentTheme.primary1,
				border: currentTheme.primary1,
				color: currentTheme.light1,
				active: {
					background: currentTheme.neutral2,
					border: currentTheme.neutral5,
					color: currentTheme.neutralA1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral5,
					color: currentTheme.neutral7,
				},
			},
			alt2: {
				background: currentTheme.neutralA1,
				border: currentTheme.neutralA1,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutralA5,
					border: currentTheme.neutralA5,
					color: currentTheme.neutralA5,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral3,
					color: currentTheme.neutral7,
				},
			},
		},
		chart: {
			primary: currentTheme.chart1,
			background: currentTheme.chart2,
		},
		checkbox: {
			active: {
				background: currentTheme.primary1,
			},
			background: currentTheme.neutral1,
			hover: currentTheme.neutral3,
			disabled: currentTheme.neutral5,
		},
		container: {
			primary: {
				background: currentTheme.neutral1,
				active: currentTheme.neutral2,
			},
			alt1: {
				background: currentTheme.neutral2,
			},
			alt2: {
				background: currentTheme.neutral3,
			},
			alt3: {
				background: currentTheme.neutral4,
			},
			alt4: {
				background: currentTheme.neutral5,
			},
			alt5: {
				background: currentTheme.neutralA4,
			},
			alt6: {
				background: currentTheme.primary1,
			},
			alt7: {
				background: currentTheme.neutralA3,
			},
			alt8: {
				background: currentTheme.dark1,
			},
			alt9: {
				background: currentTheme.primary1,
			},
			alt10: {
				background: currentTheme.primary2,
			},
		},
		font: {
			primary: currentTheme.neutralA1,
			alt1: currentTheme.neutral7,
			alt2: currentTheme.neutralA4,
			alt3: currentTheme.neutral8,
			alt4: currentTheme.neutral1,
			alt5: currentTheme.primary1,
			light1: currentTheme.light1,
			light2: currentTheme.light2,
			light3: currentTheme.light3,
			dark1: currentTheme.dark1,
			dark2: currentTheme.dark2,
		},
		form: {
			background: currentTheme.neutral1,
			border: currentTheme.neutral6,
			invalid: {
				outline: currentTheme.negative1,
				shadow: currentTheme.negative2,
			},
			valid: {
				outline: currentTheme.neutralA2,
				shadow: currentTheme.neutralA3,
			},
			disabled: {
				background: currentTheme.neutral2,
				border: currentTheme.neutral5,
				label: currentTheme.neutral7,
			},
		},
		gradient: {
			start: currentTheme.primary1,
			middle: currentTheme.primary1,
			end: currentTheme.primary2,
		},
		icon: {
			primary: {
				fill: currentTheme.neutralA1,
				active: currentTheme.neutralA4,
				disabled: currentTheme.neutralA6,
			},
			alt1: {
				fill: currentTheme.neutral4,
				active: currentTheme.neutral5,
				disabled: currentTheme.neutral3,
			},
			alt2: {
				fill: currentTheme.neutralA1,
				active: currentTheme.neutralA4,
				disabled: currentTheme.neutral3,
			},
			alt3: {
				fill: currentTheme.neutralA2,
				active: currentTheme.neutral1,
				disabled: currentTheme.neutral3,
			},
		},
		indicator: {
			primary: currentTheme.primary1,
			active: currentTheme.primary1,
			contrast: currentTheme.negative1,
		},
		link: {
			color: currentTheme.link1,
			active: currentTheme.link2,
		},
		loader: {
			primary: currentTheme.neutralA2,
		},
		overlay: {
			primary: currentTheme.overlay1,
			alt1: currentTheme.overlay2,
		},
		stats: {
			primary: currentTheme.stats.primary,
			alt1: currentTheme.stats.alt1,
			alt2: currentTheme.stats.alt2,
			alt3: currentTheme.stats.alt3,
			alt4: currentTheme.stats.alt4,
			alt5: currentTheme.stats.alt5,
			alt6: currentTheme.stats.alt6,
			alt7: currentTheme.stats.alt7,
			alt8: currentTheme.stats.alt8,
			alt9: currentTheme.stats.alt9,
			alt10: currentTheme.stats.alt10,
			alt11: currentTheme.stats.alt11,
			alt12: currentTheme.stats.alt12,
			alt13: currentTheme.stats.alt13,
			alt14: currentTheme.stats.alt14,
			alt15: currentTheme.stats.alt15,
			alt16: currentTheme.stats.alt16,
			alt17: currentTheme.stats.alt17,
		},
		row: {
			active: {
				background: currentTheme.neutral3,
				border: currentTheme.neutral2,
			},
			hover: {
				background: currentTheme.neutral2,
			},
		},
		scrollbar: {
			track: currentTheme.neutral2,
			thumb: currentTheme.neutral5,
		},
		shadow: {
			primary: currentTheme.shadow1,
			alt1: currentTheme.shadow2,
		},
		status: {
			draft: currentTheme.caution1,
			published: currentTheme.positive1,
		},
		tabs: {
			color: currentTheme.neutralA4,
			active: {
				background: currentTheme.accent1,
				color: currentTheme.neutral1,
			},
		},
		tooltip: {
			background: currentTheme.dark2,
			border: currentTheme.neutral9,
			color: currentTheme.light1,
		},
		view: {
			background: currentTheme.neutral1,
		},
		warning: {
			primary: currentTheme.negative1,
			alt1: currentTheme.negative2,
		},
	},
	typography: {
		family: {
			primary: `'DM Sans', sans-serif`,
			alt1: `'Roboto Mono', monospace`,
		},
		size: {
			xxxxSmall: 'clamp(10px, 0.85vw, 11px)',
			xxxSmall: 'clamp(11px, 1.15vw, 12px)',
			xxSmall: 'clamp(12px, 1.25vw, 13px)',
			xSmall: 'clamp(13px, 1.35vw, 14px)',
			small: 'clamp(14px, 1.45vw, 15px)',
			base: 'clamp(15px, 1.5vw, 16px)',
			lg: 'clamp(16px, 1.65vw, 18px)',
			xLg: 'clamp(18px, 1.75vw, 24px)',
			xxLg: 'clamp(28px, 2.75vw, 34px)',
			xxxLg: 'clamp(32px, 3.2vw, 42px)',
			h1: 'clamp(27px, 2.625vw, 42px)',
			h2: 'clamp(24px, 2.4375vw, 37.5px)',
			h4: 'clamp(21px, 2.25vw, 28.5px)',
			h6: 'clamp(13.5px, 1.5vw, 16.5px)',
		},
		weight: {
			thin: '200',
			light: '300',
			regular: '400',
			medium: '500',
			bold: '600',
			xBold: '700',
		},
	},
});
